services:
  shortener-auth-service:
    container_name: shortener-auth-service
    image: 533267200006.dkr.ecr.eu-central-1.amazonaws.com/diploma-auth-service:dev.latest
    ports:
      - '8181:8181'
    environment:
      - spring.datasource.url=jdbc:postgresql://shortener-postgres:5432/auth_service_database
      - spring.datasource.username=local-user
      - spring.data.redis.host=shortener-redis
      - spring.kafka.bootstrap-servers=shortener-kafka:9092
      - platform.is-test=false
    volumes:
      - ../eks/.aws:/root/.aws
    depends_on:
      - shortener-postgres
      - shortener-redis
      - shortener-kafka

  shortener-postgres:
    container_name: shortener-postgres
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: 'local-user'
      POSTGRES_PASSWORD: 'qwerty'
    volumes:
      - ../eks/init:/docker-entrypoint-initdb.d
      - shortener_postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  shortener-redis:
    container_name: shortener-redis
    image: redis:8.0-rc1-alpine
    ports:
      - '6379:6379'
    volumes:
      - shortener_redis_data:/data

  shortener-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: shortener-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  shortener-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: shortener-kafka
    depends_on:
      - shortener-zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: shortener-zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://shortener-kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  shortener-kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: shortener-kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: shortener-kafka:9092
      JVM_OPTS: "-Xms32M -Xmx64M"
    depends_on:
      - shortener-kafka

volumes:
  shortener_postgres_data:
  shortener_redis_data: