services:
  ci-auth-service:
    container_name: ci-auth-service
    image: 533267200006.dkr.ecr.eu-central-1.amazonaws.com/diploma-auth-service:dev.latest
    ports:
      - '8181:8181'
    environment:
      - spring.datasource.url=jdbc:postgresql://ci-postgres:5432/auth_service_database
      - spring.datasource.username=ci-user
      - spring.data.redis.host=ci-redis
      - spring.kafka.bootstrap-servers=ci-kafka:9092
    volumes:
      - ../ecs/.aws:/root/.aws
    depends_on:
      - ci-postgres
      - ci-redis
      - ci-kafka

  ci-postgres:
    container_name: ci-postgres
    image: postgres:16.8-alpine3.20
    environment:
      POSTGRES_USER: 'ci-user'
      POSTGRES_PASSWORD: 'qwerty'
    ports:
      - '5432:5432'
    volumes:
      - ../ecs/init:/docker-entrypoint-initdb.d

  ci-redis:
    container_name: ci-redis
    image: redis:8.0-rc1-alpine
    ports:
      - '6379:6379'

  ci-zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ci-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  ci-kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ci-kafka
    depends_on:
      - ci-zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: ci-zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://ci-kafka:9092,EXTERNAL://172.17.0.1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL